title: NodaMoney
description: NodaMoney provides a library that treats Money as a first class citizen and handles all the ugly bits like currencies and formatting.
remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: true
google_analytics: UA-83952219-1
#highlighter: rouge
